# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '8.0'

target 'SCNetworkAgent_Example' do
  pod 'SCNetworkAgent', :path => '../'
  pod 'SCNetworkKit','1.0.20'
  pod 'SCJSONUtil'
  pod 'AFNetworking', :path => './Vendor/'
end
